name: Create S3 Bucket

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  create-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # change to your region

     
